name: Create Weekly Episode Plan

on:
  schedule:
    # Workflow will run every Tuesday at 10:00AM UTC
    - cron: '0 10 * * 2'
  workflow_dispatch:
  
jobs:
  create-weekly-sync-issue:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        fetch-depth: 1
    # Create issue from template
    - uses: JasonEtco/create-an-issue@5d9504915f79f9cc6d791934b8ef34f2353dd74d
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE/minutes-of-meeting-template.md
